Fix lastScanTime Column Error - Comment Out Non-Existent Column Update
ERROR: column "lastscantime" of relation "users" does not exist

CAUSE: Code tried to update lastScanTime column after conference scan,
but this column doesn't exist in the users table schema.

FIX: Commented out the db.updateUser() call that tries to set lastScanTime
(conference.handler.ts:128-129)

TODO: Add lastScanTime column to users table schema if tracking scan
times is needed. For now, conference scan works but doesn't remember
when user last scanned.

Note: Conference scan still works correctly - it queries for new messages
and displays them. Only the "remember last scan time" feature is disabled.